ORG 000H

;WRITE CODE TO DETERMINE IF REGISTER A CONTAINS
;THE VALUE 99H.OF SO,MAKE R1=FFH;OTHERWISE,MAKE R1=0

;MOV R1,#0
;CJNE A,#99H,NEXT
;MOV R1,#0FFH


;ASSUME THAT P1 IS AN INPUT PORT CONNECTED TO A TEMPERATURE SENSOR.
;WRITE A PROGRAM TO READ THE TEMPERATURE AND TEST IT
;FOR THE VALUE 75.ACCORDING TO THE TEST RESULTS,PLACE THE 
;TEMPERATURE VALUE INTO THE REGISTER INDICATED BY FOLLOWING
; IF T= 75, A= 75
; IF T< 75, R1=T
; IF T< 75, R2=T

MOV P1,#0FFH
MOV A,P1
CJNE A,#75,OVER
SJMP EXIT

OVER: JNC NEXT
	  MOV R1,A
	  SJMP EXIT
NEXT: MOV R2,A
	  SJMP EXIT

EXIT: 
	END