ORG 000H

;WRITE A PROGRAM TO TRANSFER VALUE 41H SERIALLY 
;(ONE BIT AT A TIME ) VIA PIN P2.1.PUT TWO HIGHS
;AT THE START AND END OF THE DATA .SEND THE BYTE 
;LSB FIRST!

MOV A,#41H
SETB P2.1
SETB P2.1
MOV R5,#8

HERE:   RRC A
		MOV P2.1,C
		DJNZ R5,HERE
		SETB P2.1
		SETB P2.1		